baseURL = 'https://Daisy2025769.github.io/'
languageCode = 'zh-cn'
title = 'Daisy的个人主页' # 这里改成你的名字
theme = 'PaperMod'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # 允许文章里使用少量自定义 HTML（比如 Sources 区块的样式包裹）

[params]
  defaultTheme = "auto" # 自动跟随系统切换黑白模式

  [params.author]
    name = "Daisy"
    email = "web1091026187@gmail.com"

  # 开启首页简介模式
  [params.profileMode]
    enabled = true
    title = "Hi, I am Daisy 👋" # 首页大标题
    subtitle = "Welcome to my channel!" # 副标题/简介
    imageUrl = "avatar.jpg"
    imageTitle = "Avatar"
    imageWidth = 120
    imageHeight = 120

    # 社交按钮 (可以加微信、B站、邮箱等)
 [[params.profileMode.buttons]]
      name = "📧 Email"  # 按钮上显示的文字，可以加个emoji
      url = "mailto:web1091026187@gmail.com"  # ⚠️注意：把这里换成你的真实邮箱
 [[params.profileMode.buttons]]
      name = "📷 Instagram"
      url = "https://www.instagram.com/web1091026187/"
  
  # 顶栏导航
  [menu]
    [[menu.main]]
      identifier = "posts"
      name = "文章"
      url = "/posts/"
      weight = 10
    [[menu.main]]
      identifier = "search"
      name = "搜索"
      url = "/search/"
      weight = 20